In [ ]:
a = int('1'*3, 2) # 第二个参数表示进制
print(a)

7


In [ ]:
vector= [[1,2,3],[4,5,6],[7,8,9]]
a = [num for item in vector for num in item] # 展平为一维列表
a = sum(vector, [])
v2 = [[1,2,3],[3,2,1],[2,1,3]]
v2 = sum(v2, [])
a = list(set(v2))
print(a)

[1, 2, 3]


In [6]:
import numpy as np

v = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print('普通二层列表：',v)
a = np.array(v)
print('np数组',a)
v = a.reshape(3, 4) # 3行4列
print(v)

普通二层列表： [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
np数组 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# eval函数必考
data1 = [[[1],[2],[3],[4],[5],[6],[7],[8],[9]]]
s1 = str(data1) # 将列表完整的转为字符串
print('列表转为字符串：',s1)
s1 = str(data1).replace('[','').replace(']','') # 去掉中括号
print('去掉中括号：',s1)
# s1 = s1.replace(',','')
# print('去掉逗号：',s1)
data2 = [['a'],['b'],['c'],['d'],['e'],['f'],['g'],['h'],['i']]
s2 = str(data2).replace('[','').replace(']','')
print('去掉中括号的s2:',s2)
s3 = eval('[{z1},{z2},{z3}]'.format(z1=s1, z2=s2, z3='[10]')) # 多变量复杂结构拼接
print('eval函数：',s3)
tmp ="'老铁666'"
s4  = eval(f'[1,{tmp},3]') # 简单字符串插值
print('eval函数：',s4)
# eval函数将字符串作为python代码执行
# print([int(num) for num in str(data) if num.isdigit()])

data3 = "1,2,3,4"
s = f'[{data3}]'
result = eval(s)
print(result)


列表转为字符串： [[[1], [2], [3], [4], [5], [6], [7], [8], [9]]]
去掉中括号： 1, 2, 3, 4, 5, 6, 7, 8, 9
去掉中括号的s2: 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'
eval函数： [1, 2, 3, 4, 5, 6, 7, 8, 9, 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', [10]]
eval函数： [1, '老铁666', 3]
[1, 2, 3, 4]


In [ ]:
# 异或实现交换操作
a,b = 3, 4
a = a^b
b = a^b
a = a^b
print(a, b)
a, b = b, a
print(a, b)

4 3
3 4


In [33]:
a=9
print(6) if a > 3 else print(5)
print(6 if a > 3 else 5)
b = 6 if a > 3 else 5
print(b)

6
6
6


In [ ]:
# while和for循环可以加else子句,当while循环正常结束时,else子句会被执行,如果是break结束的,else子句不会被执行
# 专研collections库,2到3个外部库的使用，写2页左右的报告
# random库，math库
# 不超过前6章，
# itertools， 字符串正则表达式，random,numpy,collections