### 总复习:
- 第四章:哪些是re方法,哪些是字符串方法
- 考试题型安排：
    - 10个判断题1分
    - 10个选择题1分
    - 程序填空30分
    - 代码理解20分
    - 代码实践3大题(写代码和设计思路)30分

- 复习
    - python什么类型语言
        解释型，动态类型，面向对象的高级编程语言
    - 什么是对象，内置对象，非内置对象
        - 常用内置对象：列表、字典、字符串、集合、元组
    - 列表推导式重点
    - 元组和列表的关系和区别
    - 字典的基础方法
    - 集合
    - 双分支表达式(A if A else B)
    - 字符串：(补不考正则表达式)
        - 短驻留，长不驻留
        - 浅拷贝、深拷贝
        - 格式化format
        - join是字符串方法
        - strip()
        - eval
        - endswith,startswith
    - re模块常用方法（实验中的字符串处理部分）
        - 匹配对象
        - 编译
    - 函数
        - 装饰器
        - 函数嵌套
        - 函数闭包
    - lambda表达式
    - map,filter
    - yeild语句将函数转为生成器
    - 面向对象
        - self
        - 类方法，静态方法
        - 私有成员、公有成员
        - 继承
        - 动态添加数据成员
    - 第三方库
        - random
        - collections
        - itertools
        - math
        



#### 第六章
- 第六章：类的固有函数；子类怎么调用父类构造函数


In [2]:
# 子类如何调用父类的构造方法
class Parent:
    def __init__(self):
        print("Parent init")

class Child(Parent):
    def __init__(self):
        super().__init__()
        # 或者
        # Parent.__init__(self)

- \_xxx 保护成员，这样的对象不能用from module import *导入
- \_\_xxx\_\_ 表示系统预定义的特殊成员，不能随意定义和增加
- \_\_ 类中的私有成员，子类不能访问，可通过 对象名.\_类名\_\_xxx访问

In [ ]:
class MyClass:
    def __init__(self):
        self.__private_var = 42  # 实际会被存储为 _MyClass__private_var

obj = MyClass()

# 通过改写后的名称访问
print(obj._MyClass__private_var)  # 输出: 42

42


- 类中定义的方法有四类：公有方法、私有方法、静态方法、类方法
    - 静态方法@staticmethod，类方法@classmethod，否则python默认为普通方法。
    - 静态方法不关心类和实例。类方法能访问和修改类属性。

In [ ]:
class Root:
    __total = 0
    def __init__(self, v):
        self.__value = v
        Root.__total += 1
    
    def show(self):
        print('self.__value:',self.__value)
        print('Root.__total:',Root.__total)
        
    @classmethod # 类方法
    def classShowTotal(cls):
        print(cls.__total)
    
    @staticmethod # 静态方法
    def staticShowTotal():
        print(Root.__total)
# 示例
r = Root(3)

r.show()
Root.show(r)

self.__value: 3
Root.__total: 1
self.__value: 3
Root.__total: 1


- 属性

In [ ]:
class Test:
    def __init__(self, value):
        self.__value = value

    @property # 将方法转为属性，且只读，不允许修改
    def value(self):
        return self.__value

t = Test(3)
print(t.value)
t.v = 10 # 可以对实例动态添加新属性
print(t.v)
del t.v # 可删除，但value不可删除


3
10


In [ ]:
class Test:
    def __init__(self, value):
        self.__value = value
    def __get(self):
        return self.__value
    def __set(self, v):
        self.__value = v
    def __del(self):
        del self.__value
    value = property(__get, __set, __del) # 修饰器，定义可读可写可删除属性
    
    def show(self):
        print(self.__value)
t = Test(3)
print(t.value)
t.value = 5
print(t.value)
t.show()
del t.value

3
5
5


In [ ]:
'''类的魔法方法
__new__()类的静态方法，确定是否要创建对象
__init__()构造方法，创建对象时自动调用
__del__()析构方法，释放对象时自动调用
__add__() +
__sub__() -
__mul__() *
__truediv__() /
__floordiv__() // 整除
__mod__() % 取余
__pow__() ** 幂
__eq__() ==  __ne__() !=  __lt__() <  __le__() <=   __gt__() >   __ge__() >= 
__lshift__() <<  __rshift__() >>  位运算
__and__() & __or__() |  __invert__() 取反  __xor__() ^异或
__iadd__() +=  __isub__() -=  __imul__() *=  __itruediv__() /=  __ifloordiv__() //=  __imod__() %=  __ipow__() **=
__pos__() 正号 __neg__() 负号
__contains__() in
__len__() len()
__str__() str()
__call__() 可调用对象，对象名()时，会执行该方法
'''

#### 第五章
- 必考点
    - 嵌套函数
    - 修饰器

In [ ]:
'''
解释型语言
动态类型语言：变量类型在运行是确定，
面向对象语言：支持封装、继承和多态
内置对象：list,dict,str,set,tuple
非内置对象：自定义类
'''

# 列表推导式专题复习
num1 = [x for x in range(10)]
print(num1)

num2 = [x for x in range(10) if x % 2 == 0]
print(num2)

num3 = [x for x in range(1,101) if x % 3 == 0 and x % 5 == 0]
print(num3)

letters = [a + b for a in 'abc' for b in 'xyz']
print(letters)

fruits = ['apple','banana', 'cherry']
dict1 = {fruit:len(fruit) for fruit in fruits}
print(dict1) 

a = [[1,2],[3,4],[5,6]]
trans_a = [[row[i] for row in a] for i in range(2)]
print(trans_a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[15, 30, 45, 60, 75, 90]
['ax', 'ay', 'az', 'bx', 'by', 'bz', 'cx', 'cy', 'cz']
{'apple': 5, 'banana': 6, 'cherry': 6}
[[1, 3, 5], [2, 4, 6]]


In [81]:
# 列表
# 列表的创建
a = [1,2,3]
print(id(a))
a[2] = 4
print(id(a))
a.insert(0,'a')
print(id(a))
b = a*3
print(id(b))

# 使用*号创建列表时，创建的是原来元素的引用
x = [[123] * 2] * 3
print(x)
print('输出id：x[0][0]和x[0][1]')
print(id(x[0][0]))
print(id(x[0][1]))
x[0][0] = 1
print(x)
print([id(row) for row in x])
# del x[0][1]
x.remove([1, 123])
print(x)
print(id(x[0][0]))
a = list('hello world')
b = list(range(1,10,2))
print(a)
print(b)

# 列表元素的增加
alist = [3,4,5]
alist += [6,7,8]
print(alist)
# append()方式是原地修改列表，速度较快
alist.append(9)
print(alist)
alist.insert(-1, 99)
print(alist)
print(alist.index(99))
print(round(7.495,2))

# extend方法，将一个可迭代对象的元素添加到列表末尾
alist.extend([10,11,12])
print(alist)
alist.pop()
print(alist)

print([3] in [1,2,3])

2472719048064
2472719048064
2472719048064
2472719054464
[[123, 123], [123, 123], [123, 123]]
输出id：x[0][0]和x[0][1]
140733031520504
140733031520504
[[1, 123], [1, 123], [1, 123]]
[2472719049536, 2472719049536, 2472719049536]
[[1, 123], [1, 123]]
140733031516600
['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
[1, 3, 5, 7, 9]
[3, 4, 5, 6, 7, 8]
[3, 4, 5, 6, 7, 8, 9]
[3, 4, 5, 6, 7, 8, 99, 9]
6
7.5
[3, 4, 5, 6, 7, 8, 99, 9, 10, 11, 12]
[3, 4, 5, 6, 7, 8, 99, 9, 10, 11]
False


In [ ]:
# 集合的基本操作
s1 = set() # 创建空集合
# 不能使用s1={},会创建字典

s1 = set([1,2,2,3])
print(s1) # 集合元素是唯一的
s1.add(4) # 添加元素
print(s1)
s2 = {4,4,5,5,6}
print(s2)
s2.clear()
print(s2)

{1, 2, 3}
{1, 2, 3, 4}
{4, 5, 6}
set()


In [48]:
# random库用法
import random 
x = random.random() # 生成0-1之间浮点数
print(x)

num = random.randint(1,10) # 返回[1,10]闭区间的整数
num = random.randrange(1,10) # 返回[1,10)开区间的整数
num = random.randrange(0,10,2) # 返回0，2，4，6，8中的随机数

x = random.uniform(1,10) # 返回[1,10]闭区间的浮点数
print(x)
print(num)

a = [1,2,3,4,5]
b = random.choice(a) # 随机选择列表中的一个元素
b = random.choices(a,k=10) # 随机选择列表中的10个元素，允许重复
c = random.sample(a,k=5) # 随机选择列表中的5个元素，不允许重复
print(b)
print(c)

# 设置随机种子，使结果可重现
random.seed(43)
num1 = random.random()
random.seed(43)
num2 = random.random()
print(num1)
print(num2)
print(num1 == num2)

0.6962243226370528
7.0448208770599035
4
[3, 3, 1, 3, 2, 5, 3, 4, 3, 1]
[1, 5, 2, 4, 3]
0.038551839337380045
0.038551839337380045
True


In [92]:
# numpy库的使用
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(a.shape) # 数组的形状
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape) # 数组的形状
print(b.ndim) # 数组的维度
print(b.size) # 元素个数
print(b.dtype) # 数组的数据类型
b = b.reshape(3,2)
print(b)
zeros = np.zeros(5)
ones = np.ones((2,5))
print(zeros)
print(ones)

c = np.arange(1,10,2)
print(c)

e = np.linspace(0,1,2) # 创建等间隔数组
print(e)

random_array = np.random.rand(2,2) # 生成0-1之间的随机数，数组形状为2，2
print(random_array) # 创建随机数组

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0,0])
print(a[2,3])


[1 2 3 4 5]
(5,)
[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32
[[1 2]
 [3 4]
 [5 6]]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1 3 5 7 9]
[0. 1.]
[[0.87481644 0.04639751]
 [0.14504527 0.75284776]]
1
12


In [60]:
a = [1,2,3]
b = [4,5,6]
c = zip(a,b) # 将多个可迭代对象对应位置组合为元组，返回可迭代对象
print(list(c))

for yi,er in enumerate('hello world'):
    print((yi,er),end=',')
print()

# 列表推导式
[(x,y) for x in range(3) for y in range(3)]
# 列表推导式实现矩阵转置
matrix = [[1,2,3],[4,5,6],[7,8,9]]
d = [[row[i] for row in matrix] for i in range(3)]
print(d)
# 使用map函数实现矩阵转置
d = list(map(list, zip(*matrix))) # 对matrix进行解包，提取每个可迭代对象对应位置的元素
print(d)

# 三目运算符，条件表达式，三元运算符
x = 1
a = '666' if x > 0 else '999'
print(a)

# 使用列表实现向量运算
import random
x = [random.randint(1,10) for _ in range(5)]
y = list(map(lambda x: x + 5, x))
print(x)
print(y)
import operator
z = sum(map(operator.mul, x,y)) # 向量内积，函数式编程
z2 = sum(i*j for i, j in zip(x,y))
print(z)
print(z2)

[(1, 4), (2, 5), (3, 6)]
(0, 'h'),(1, 'e'),(2, 'l'),(3, 'l'),(4, 'o'),(5, ' '),(6, 'w'),(7, 'o'),(8, 'r'),(9, 'l'),(10, 'd'),
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 4, 7], [2, 5, 8], [3, 6, 9]]
666
[10, 6, 10, 9, 7]
[15, 11, 15, 14, 12]
576
576


In [ ]:
# 元组
x = ([1,2], 6)
x[0][1] = 3
# x[0] += [4] 报错
print(x)

# 序列解包
s = {'a':1, 'b':2, 'c':3}
a,b,c = s.items()
print(a,b,c)
a = [*range(4), 5]
print(a)

# 字典的访问
d = {'a':1, 'b':2, 'c':3}
print(d.get('a'))
e = d.pop('c') # 会返回被删除的元素
print(e)

x = ['a', 'b', 'c']
y = ['d', 'e', 'f']
z = {i:j for i,j in zip(x,y)}
print(z)

([1, 3], 6)
('a', 1) ('b', 2) ('c', 3)
[0, 1, 2, 3, 5]
1
3
{'a': 'd', 'b': 'e', 'c': 'f'}


In [80]:
# 集合
a = {1,2,3,4}
a.pop() # 只能随机删除一个元素
a.remove(2)
print(a)
# 集合支持交集、并集、差集，对称差集（异或）
print('集合运算')
a = {8,9,10,11,12,13}
b = {0,1,2,3,7,8}
t1 = a & b
t2 = a | b
t3 = a - b
t4 = a ^ b
print(t1)
print(t2)
print(t3)
print(t4)
# 集合比较大小用来判断子集和超集
a = {1,2,3}
b = {1,2,3,4}
print(a < b) # True

{3, 4}
集合运算
{8}
{0, 1, 2, 3, 7, 8, 9, 10, 11, 12, 13}
{9, 10, 11, 12, 13}
{0, 1, 2, 3, 7, 9, 10, 11, 12, 13}
True


In [ ]:
# while else 语句,当while循环正常结束时，执行else语句，或者while中条件不成立，执行else语句
# 如果while循环被break中断，则不执行else语句
a = 1
while a < 5:
    print('in while')
    a += 1
    if a == 4:
        break
else:
    print('in else')
    
import itertools
team = ['A', 'B', 'C', 'D']
group = len(tuple(itertools.combinations(range(6), 2)))
print(group) # 组合

from itertools import compress # 根据选择器中True的结果选择元素,类似于filter
scores = [75,80,93,85,72]
passed = [score >= 80 for score in scores]
result = list(compress(scores, passed))
print(result)
# compress和filter的区别
# result = compress(data, selectors) 通过bool序列选择元素，需要等长序列，直接用bool值筛选，效率较高
# result = filter(function, iterable)通过函数判断选择元素，只要一个序列和函数，对每个元素调用函数，效率较低


in while
in while
in while
15
[80, 93, 85]


In [ ]:
# 字符串
t = ' hello, Python World! nice to meet you.  '
pos = t.find('Python') # 查找字符串，返回索引
print(pos)
pos = t.index('Python') # 从右边查找字符串，返回索引
print(pos)
upper_t = t.upper()
print(upper_t)
lower_t = t.lower()
print(lower_t)
cap_t = t.capitalize() # 对字符串首字母大写
print(cap_t)
title_t = t.title() # 对每个单词首字母大写
print(title_t)
words = t.split(' ') # 返回列表
lines = t.splitlines() # 按行分割
print(words)
text = '-'.join(words)
print(text) # 将列表元素连接成字符串
clean = t.strip()
print(clean) # 去除首尾空格    
clean = clean.rstrip('.')
print(clean) # 去除右边的点

t = 'Hello123'
# print(t.isalnum())
# print(t.isalpha())
# print(t.isdigit())
# print(t.islower())
# print(t.isupper())
# print(t.isspace()) # 是否是空白字符

t = 'hello,{name}'.format(name='Python')
print(t)
t = '{:.2f}'.format(3.1415926)
print(t)
t = '{:0>5}'.format(3)
print(t) # 左填充
t = '{:0<5}'.format(3)
print(t) # 右填充
t = '{:0^5}'.format(3) 
print(t) # 居中对齐
t = '{:}'.format(3)
print(t)

t = 'Hello'
print(t.ljust(10)) # 左对齐
print(t.rjust(10)) # 右对齐
print(t.center(10)) # 居中对齐
print(t.zfill(10)) # 用0填充

8
8
 HELLO, PYTHON WORLD! NICE TO MEET YOU.  
 hello, python world! nice to meet you.  
 hello, python world! nice to meet you.  
 Hello, Python World! Nice To Meet You.  
['', 'hello,', 'Python', 'World!', 'nice', 'to', 'meet', 'you.', '', '']
-hello,-Python-World!-nice-to-meet-you.--
hello, Python World! nice to meet you.
hello, Python World! nice to meet you
hello,Python
3.14
00003
30000
00300
3
Hello     
     Hello
  Hello   
00000Hello


In [ ]:
import re
t = 'alpha. beta...gama delta'
r = re.split(r'[\.]+',t) # 根据模式匹配项分割字符串
print(r) # 按照.分割
r = re.split(r'[\.]+',t,maxsplit=1)
print(r) 
pat = '[a-zA-Z]+'
r = re.findall(pat,t)
print(r) # 查找所有匹配项
s = 'a s d'
r =re.sub('a|s','good',s)
print(r)

# compile将正则表达式字符串模式编译成正则表达式对象，提高多次匹配时的效率
pattern = re.compile(r'\w+g\b')
r = pattern.findall('hello,goodbye,good morning')
print(r)


['alpha', ' beta', 'gama delta']
['alpha', ' beta...gama delta']
['alpha', 'beta', 'gama', 'delta']
good good d
['morning']


In [ ]:
import re
t = 'hello python, hello world'
m1 = re.match(r'hello',t) # 只检查开头
print(m1)
m2 = re.match(r'python',t)
print(m2)
s1 = re.search(r'python',t)
print(s1)
s2 = re.search(r'hello',t)
print(s2)

<re.Match object; span=(0, 5), match='hello'>
None
<re.Match object; span=(6, 12), match='python'>
<re.Match object; span=(0, 5), match='hello'>


In [55]:
# 函数章节，高级话题
# map函数
a = list(map(str, range(5)))
print(a)
def add5(v):
    return v + 5
a = list(map(add5, range(5)))
print(a)
def add(x,y):
    return x + y
a = list(map(add, range(5), range(5,10)))
print(a)

# reduce函数
from functools import reduce
seq = [1,2,3,4,5]
a = reduce(lambda x,y,:x+y,seq)
print(a) # 计算序列的和
b = reduce(add,map(str,seq))
print(b)

# filter函数
seq = ['foo','x41','?!','***']
def func(x):
    return x.isalnum()
a = list(filter(func, seq))
print(a) # 过滤掉非字母数字的元素
b = list(filter(str.isalpha, seq)) # 直接使用类方法
print(b)

['0', '1', '2', '3', '4']
[5, 6, 7, 8, 9]
[5, 7, 9, 11, 13]
15
12345
['foo', 'x41']
['foo']


In [62]:
# 函数生成器
def gen():
    cnt = 1
    while True:
        yield cnt
        cnt += 1
g = gen()
print(next(g))
print(g.__next__())

# 函数嵌套
def linear(a,b):
    def result(x):
        return a * x + b
    return result
f = linear(2,3)
print(f(5))

1
2
13


In [73]:
# 函数修饰器
def before(func):
    def wrapper(*args, **kwargs):
        print('before function called.')
        return func(*args, **kwargs)
    print('all done.') 
    return wrapper

def after(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        print('after function called.')
        return result
    print('inner done.')    
    return wrapper

@before
@after
def test():
    print('test function called.')

print('装饰器已经定义好了，还没执行函数')
a = test()



inner done.
all done.
装饰器已经定义好了，还没执行函数
before function called.
test function called.
after function called.


In [ ]:
# 静态方法和类方法的区别演示

class Demo:
    class_var = 0

    def __init__(self):
        Demo.class_var += 1

    @staticmethod
    def static_func():
        print("静态方法：不能访问类属性和实例属性")
        # print(self)  # 实例方法不能访问
        # print(cls)   # 类方法不能访问

    @classmethod
    def class_func(cls):
        print("类方法：可以访问和修改类属性")
        print("当前类:", cls)
        print("类属性class_var:", cls.class_var)
        cls.class_var += 10

d1 = Demo()
d2 = Demo()

Demo.static_func()   # 只能做普通功能，不能访问类和实例的数据
Demo.class_func()    # 可以访问和修改类属性

print("类属性class_var现在是：", Demo.class_var)



静态方法：不能访问类属性和实例属性
类方法：可以访问和修改类属性
当前类: <class '__main__.Demo'>
类属性class_var: 2
类属性class_var现在是： 12


In [13]:
# 继承方法
class Person(object):
    def __init__(self, name='',age=20,sex='man'):
        self.name = name
        self.age = age
        self.sex = sex

class Teacher(Person):
    def __init__(self, name='',age=30,sex='man',department='Computer'):
        super().__init__(name,age,sex)

liuyang = Teacher('liuyang',10,'man')
print(liuyang.__dict__)

{'name': 'liuyang', 'age': 10, 'sex': 'man'}


#### 个人综合项目总结
- pychart多端通信系统，使用的库：
    - tkinter:用于实现图形化聊天窗口界面，包括消息显示、好友列表等
        - Tk()创建主窗口
        - Button()创建按钮控件
        - Entry()单行文本输入框
        - Text()多行文本输入框
        - Scrollbar()滚动条控件
        - Menu()菜单栏控件
        - mainloop()进入消息循环，显示窗口
        - bind(event,handler)事件绑定，如按键、点击
        - messagebox()弹出消息提示框
        - tkFont.Font()字体设置
    - socket:实现基于TCP协议的网络通信，支持多客户端之间的全双工通信，实现方式是一个中心服务器，负责多个客户端之间消息的收发。
        - socket.socket()，创建新的socket对象
        - listen()监听传入连接
        - accept()接受连接，返回
        - connect()客户端连接到指定服务器
        - send(data)发送数据
        - recv()接收数据
        - close()关闭socket连接
    - threading:在服务端启用多线程，用于启动多个socket连接，实现多端同时在线聊天。
        - threading.Thread(target=,args=)创建一个线程对象，指定运行的目标函数和参数
        - start()启动线程
        - join()等待线程结束
        - setDaemon()设置为守护线程


In [6]:
# 字符串综合处理
pattern = 'abc'
str = 'abcabcbcbbabcbacabacbbacbac'
def check(pattern, str):
    pat = set(pattern)
    for s in str:
        if s not in pat:
            return False
    return True

print(check(pattern, str))



True
